name: webrtc-stund
dev:
  cpu: 256
  mem: 512
  minimumPercentOfInstances: 100
  maximumPercentOfInstances: 200
  instances: 1
  policyFile: "dev.taskrole.json"

staging:
  cpu: 256
  mem: 512
  minimumPercentOfInstances: 100
  maximumPercentOfInstances: 200
  instances: 1
  policyFile: "dev.taskrole.json"

prod:
  cpu: 256
  mem: 512
  minimumPercentOfInstances: 100
  maximumPercentOfInstances: 200
  instances: 1
  policyFile: "dev.taskrole.json"

port: 3478
protocol: TCP
healthPort: 3478
launchType: FARGATE
